### ISSUE TITLE
Using emailjs-mime-parser

### ISSUE THREAD

**Issue by abhilashabhatia** [emailjs/emailjs-mime-parser#30] opened 2018-04-18 07:29 UTC
I imported the library using 
const mimeParser = require('emailjs-mime-parser');

Now I am trying to use it with below syntax

mimeParser.parse(event.body);

where event.body is the raw email body received by POST endpoint.

What am I missing?

**Comment by felixhammerl** [comment] 2018-04-20 06:00
Sounds about right. You forgot to mention what the problem is you're seeing...

**Comment by felixhammerl** [comment] 2018-04-21 20:00
Would you have anything I can debug your problem with? It's really hard to tell what's going on considering I have no information at all about your problem ...

**Comment by felixhammerl** [comment] 2018-05-01 17:28
Closing this issue due to the absence of information. Feel free to add information when available or someone happens to have the same problem.

**Closed by felixhammerl** 2018-05-01 17:28 UTC
